# Generated by Django 2.1.4 on 2019-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partitions',
            options={'ordering': ('sort',), 'verbose_name': 'Страницы', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AddField(
            model_name='partitions',
            name='sort',
            field=models.SmallIntegerField(default=1, max_length=2, verbose_name='Порядок'),
        ),
    ]
