# Generated by Django 2.1.4 on 2019-01-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190113_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardmodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='standardmodel',
            name='shortdesc',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='partitions',
            name='sort',
            field=models.SmallIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
