# Generated by Django 2.1.4 on 2019-01-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190114_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardmodel',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='standartdoors',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Цена от'),
        ),
    ]
