# Generated by Django 2.1.4 on 2019-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0001_initial'),
        ('core', '0004_auto_20190120_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitions',
            name='catalog',
            field=models.ManyToManyField(blank=True, to='photolog.Catalog', verbose_name='Каталоги'),
        ),
        migrations.AlterField(
            model_name='standardmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание html'),
        ),
        migrations.AlterField(
            model_name='standartdoors',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание html'),
        ),
    ]
