# Generated by Django 2.1.4 on 2019-03-10 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, verbose_name='Заголовок в URL')),
                ('title', models.CharField(max_length=200, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Типы изделий',
            },
        ),
        migrations.RemoveField(
            model_name='standartdoors',
            name='materials',
        ),
        migrations.AlterModelOptions(
            name='standardmodel',
            options={'verbose_name': 'Базовая модель', 'verbose_name_plural': 'Базовые модели'},
        ),
        migrations.AlterModelManagers(
            name='homepage',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_content',
            field=models.TextField(blank=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='send_content',
            field=models.TextField(blank=True, verbose_name='Текст для "Напишите нам"'),
        ),
        migrations.AlterField(
            model_name='standardmodel',
            name='type_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProductType', verbose_name='Тип изделия'),
        ),
        migrations.DeleteModel(
            name='StandartDoors',
        ),
    ]
