# Generated by Django 2.1.4 on 2019-03-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190310_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Данные главной страницы', 'verbose_name_plural': 'Данные главной страницы'},
        ),
        migrations.AlterModelManagers(
            name='homepage',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title',
        ),
    ]
