# Generated by Django 2.1.7 on 2019-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190312_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitions',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover', verbose_name='Обложка'),
        ),
    ]
