# Generated by Django 3.0.1 on 2019-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191011_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitions',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
