# Generated by Django 2.1.4 on 2019-01-11 18:49

from django.db import migrations, models
import django.db.models.deletion
import photolog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=photolog.models.OverwriteStorage(), upload_to='photolog', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='PhotoObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photolog.Catalog')),
            ],
            options={
                'verbose_name': 'Фотообъект',
                'verbose_name_plural': 'Фотообъекты',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='phobj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photolog.PhotoObject'),
        ),
    ]
