# Generated by Django 2.1.4 on 2019-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='photolog', verbose_name='Изображение'),
        ),
    ]
