# Generated by Django 2.2.5 on 2019-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0002_auto_20190214_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoobject',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
    ]
