# Generated by Django 2.2.5 on 2019-10-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0003_auto_20191002_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoobject',
            name='shortdesc',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Краткое описание'),
        ),
    ]
