# Generated by Django 2.1.4 on 2019-02-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190214_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='files',
        ),
        migrations.AddField(
            model_name='contact',
            name='files',
            field=models.ManyToManyField(blank=True, to='contact.Files', verbose_name='Файлы'),
        ),
    ]
