# Generated by Django 2.1.4 on 2019-02-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20190215_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='files',
        ),
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contact', verbose_name='Файл'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
