# Generated by Django 2.1.4 on 2019-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20190219_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='contact', verbose_name='Файл'),
        ),
    ]
