# Generated by Django 2.1.4 on 2018-12-21 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Краткое описание')),
                ('to_publish', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('cover', models.ImageField(blank=True, height_field=600, max_length=200, null=True, upload_to='cover', verbose_name='Обложка', width_field=600)),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='url статьи')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Краткое описание')),
                ('to_publish', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
    ]
