# Generated by Django 2.1.4 on 2018-12-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181223_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='to_publish',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='to_publish',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='rubric',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10),
        ),
    ]
