# Generated by Django 2.1.4 on 2019-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181230_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='cover', verbose_name='Обложка'),
        ),
    ]
